
services:
  traefik:
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
      - "--providers.file.filename=/dynamic.yml"
      - "--providers.file.watch=true"
    ports:
      - "80:80"
