

services:
  creartstamp-node:
    image: node:20-alpine
    container_name: creartstamp_node
    working_dir: /app
    volumes:
      - ./CreartStamp:/app
    command: sh -c "npm install && tail -f /dev/null" # Instala dependencias y queda en espera
    networks:
      - creartstamp_net
    labels:
      - "traefik.enable=false" # No lo exponemos a Traefik (solo interno)

  creartstamp-nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: creartstamp_nginx
    restart: unless-stopped
    depends_on:
      - creartstamp-node
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.creartstamp.rule=Host(`creartstamp.tudominio.cl`)" # ⚡ CAMBIAR a tu dominio real
      - "traefik.http.services.creartstamp.loadbalancer.server.port=80"
    networks:
      - creartstamp_net

  traefik:
    image: traefik:v2.10
    container_name: creartstamp_traefik
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=nicholasapz7@gmail.com" # ⚡ CAMBIAR si quieres
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--api.dashboard=true"
      - "--providers.file.filename=/dynamic.yml"
      - "--providers.file.watch=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/traefik.yml
      - ./traefik/dynamic.yml:/dynamic.yml
      - ./traefik/letsencrypt:/letsencrypt
    networks:
      - creartstamp_net

networks:
  creartstamp_net:
    external: true
